=== EsraaMahmoudMohamed/xml-project-/employee.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT employees (employee+)>
<!ELEMENT employee (name, gender, phone, email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== EsraaMahmoudMohamed/xml-project-/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "employee.dtd">
<employees><employee><name>amal</name><gender>female</gender><phone>3621566</phone><email>amal@yahoo.com</email></employee><employee><name>esraa</name><gender>female</gender><phone>0123544487844</phone><email>esraa@yahoo.com</email></employee></employees>
